CREATE TABLE IF NOT EXISTS tokens (
    id SERIAL PRIMARY KEY,
    scope VARCHAR(20) NOT NULL,
    expires TIMESTAMP WITH TIME ZONE NOT NULL,
    token_hash BYTEA NOT NULL,
    user_id INT NOT NULL REFERENCES users ON DELETE CASCADE
);